package nl.whitehorses.departmentservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-04-21T15:44:32.496+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "DepartmentService", 
                  wsdlLocation = "DepartmentService.wsdl",
                  targetNamespace = "http://whitehorses.nl/DepartmentService") 
public class DepartmentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://whitehorses.nl/DepartmentService", "DepartmentService");
    public final static QName GetDepartmentByIdSoap12 = new QName("http://whitehorses.nl/DepartmentService", "GetDepartmentByIdSoap12");
    static {
        URL url = DepartmentService.class.getResource("DepartmentService.wsdl");
        if (url == null) {
            url = DepartmentService.class.getClassLoader().getResource("DepartmentService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(DepartmentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DepartmentService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DepartmentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DepartmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DepartmentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DepartmentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DepartmentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetDepartmentById
     */
    @WebEndpoint(name = "GetDepartmentByIdSoap12")
    public GetDepartmentById getGetDepartmentByIdSoap12() {
        return super.getPort(GetDepartmentByIdSoap12, GetDepartmentById.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDepartmentById
     */
    @WebEndpoint(name = "GetDepartmentByIdSoap12")
    public GetDepartmentById getGetDepartmentByIdSoap12(WebServiceFeature... features) {
        return super.getPort(GetDepartmentByIdSoap12, GetDepartmentById.class, features);
    }

}
