package nl.whitehorses.departmentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-04-21T15:44:32.469+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://whitehorses.nl/DepartmentService", name = "GetDepartmentById")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetDepartmentById {

    @WebResult(name = "DepartmentServiceResponse", targetNamespace = "http://whitehorses.nl/DepartmentService", partName = "out")
    @WebMethod(action = "http://whitehorses.nl/DepartmentService/GetDepartmentById")
    public DepartmentServiceResponse getDepartmentById(
        @WebParam(partName = "in", name = "DepartmentServiceRequest", targetNamespace = "http://whitehorses.nl/DepartmentService")
        DepartmentServiceRequest in
    );
}
